/**
 * Compose service for an approved game server (design invariant 7): untrusted tenant, isolated
 * network, no privileges, bounded resources. Values are validated upstream (game id rules,
 * team-registry image), so plain string building is safe here.
 */
export interface GameServerSpec {
  gameId: string;
  image: string;
  protocol: string;
  approvedAt: Date | null;
}

export interface ComposeTarget {
  /** `https://<id>.srv.<game domain>` for this game. */
  publicUrl: string;
  /** Platform API origin (game servers use the public API, never internal services). */
  apiOrigin: string;
  cpus?: string;
  memory?: string;
}

export function renderGameServerCompose(s: GameServerSpec, t: ComposeTarget): string {
  const name = `game-${s.gameId}`;
  const host = new URL(t.publicUrl).host;
  return `# ${s.gameId} game server (Tier 2), approved ${s.approvedAt?.toISOString() ?? '—'}.
# Generated by the platform API from the approved image; do not edit — download again after a
# new approval. Run next to the platform stack:
#   docker compose -f infra/compose.yml -f infra/game-servers/${s.gameId}.yml up -d ${name}
services:
  ${name}:
    image: ${s.image}
    restart: unless-stopped
    read_only: true
    user: '10001:10001'
    cap_drop: [ALL]
    security_opt: ['no-new-privileges:true']
    tmpfs:
      - /tmp:size=64m,mode=1777
    deploy:
      resources:
        limits:
          cpus: '${t.cpus ?? '1.0'}'
          memory: ${t.memory ?? '512M'}
          pids: 256
    environment:
      GAME_ID: ${s.gameId}
      PROTOCOL_VERSION: '${s.protocol}'
      PORT: '8080'
      # Verify players with the platform's game tokens (aud game:${s.gameId}).
      PLATFORM_JWKS_URL: ${t.apiOrigin}/.well-known/jwks.json
      TOKEN_ISSUER: ${t.apiOrigin}
      TOKEN_AUDIENCE: game:${s.gameId}
    expose: ['8080']
    # games-net only: no database, storage, or platform-internal networks.
    networks: [games-net]
    logging:
      driver: json-file
      options: { max-size: 10m, max-file: '3' }
    labels:
      traefik.enable: 'true'
      traefik.docker.network: games-net
      traefik.http.routers.${name}.rule: Host(\`${host}\`)
      traefik.http.routers.${name}.middlewares: ${name}-nocookie
      traefik.http.services.${name}.loadbalancer.server.port: '8080'
      # No cookies on the game domain (design invariant 3).
      traefik.http.middlewares.${name}-nocookie.headers.customresponseheaders.Set-Cookie: ''
`;
}
